# Generated by Django 4.2.13 on 2024-07-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('date', 'time')},
        ),
    ]
